import Navbar from "@/components/Layouts/Navbar";
import "./globals.css";
import { navbarData } from "@/configs/datas/navbar";
import Footer from "@/components/Layouts/Footer";

export const metadata = {
  title: "Hello",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>
      <body>
        <header>
          <Navbar />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
